Removed redundant scoping of constructor in FLocalizationTargetSettings that was causing warnings.
Fixes this error:
 mono: Editor/LocalizationDashboard/Private/LocalizationTargetTypes.h:243:31: error: extra qualification on member 'FLocalizationTargetSettings'

#lockdown Zachary.EdgertonJones

[CL 2521860 by Saul Abreu in Main branch]