Copying //UE4/Dev-Blueprints to Dev-Main (//UE4/Dev-Main)
#lockdown Nick.Penwarden

==========================
MAJOR FEATURES + CHANGES
==========================

Change 2806214 on 2015/12/16 by Michael.Schoell

	Connection draw policy refactored into a factory system.

	PR#1663
	#jira UE-22123 - GitHub 1663 : Implement PinConnectionPolicy factory system

Change 2806845 on 2015/12/17 by Maciej.Mroz

	Blueprint C++ Conversion: fixed varioaus problem.
	Some limitations of included header list were reverted :(
	Any compilation-time optimization are premature (as far as Orion cannot be compiled).

	#codereview Dan.Oconnor

Change 2806892 on 2015/12/17 by Maciej.Mroz

	Blueprint C++ Conversion: fixed compilation error "fatal error C1001: An internal error has occurred in the compiler."

Change 2807020 on 2015/12/17 by Michael.Schoell

	Recursively expand all tree items in graph context menus or My Blueprint window by holding shift when clicking on an arrow.

Change 2807639 on 2015/12/17 by Maciej.Mroz

	BP C++ conversion: Fix for const-correctness. Included generated headers in structs.

Change 2807880 on 2015/12/17 by Mike.Beach

	PR #1865 : Render Kismet graph pin color box with alpha
	https://github.com/EpicGames/UnrealEngine/pull/1865

	#github 1865
	#1865

	#jira UE-23863

Change 2808538 on 2015/12/18 by Maciej.Mroz

	Workaround for UE-24467. Some corrupted files can be opened and fixed.

	#codereivew Dan.Oconnor, Michael.Schoell

Change 2808540 on 2015/12/18 by Maciej.Mroz

	BP C++ conversion: fixed const-correctness related issues

Change 2809333 on 2015/12/18 by Phillip.Kavan

	[UE-23452] SCS/UCS component instancing optimizations

	change summary:
	- added FArchive::FCustomPropertyListNode
	- modified various parts of serialization code to accomodate custom property lists
	- added cooked component instancing data + supporting APIs to UBlueprintGeneratedClass

Change 2810216 on 2015/12/21 by Maciej.Mroz

	Blueprint C++ Conversion:
	- Fixed Compiler Error C2026 (too big string)
	- Fixed a lot of errors related to const correctness. "NativeConst" and "NativeConstTemplateArg" MetaData added.
	- Fixed bunch of problems with TEnumAsByte
	- Fixed for error C2059: syntax error : 'bad suffix on number' - when struct name starts with a digit
	- Fixed int -> bool  conversion

	#codereview Mike.Beach, Dan.Oconnor, Steve.Robb

Change 2810397 on 2015/12/21 by Maciej.Mroz

	Blueprint C++ Conversion: Fixed Compiler Error C1091 (too big string)

Change 2810638 on 2015/12/21 by Dan.Oconnor

	Timers for measuring VM overhead, stats for tracking individual script functions improved (now nicludes ProcessEvent). Stats system is expected to avoid double counting for object and function stats.

Change 2811038 on 2015/12/22 by Phillip.Kavan

	[UE-23452] Fix uninitialized variables in cooked component data.

	- should eliminate crashes introduced by last change

Change 2811054 on 2015/12/22 by Phillip.Kavan

	[UE-23452] Additional fix for uninitialized USTRUCT property.

Change 2811254 on 2015/12/22 by Dan.Oconnor

	More script function detail in stats

Change 2811325 on 2015/12/22 by Maciej.Mroz

	Blueprint C++ Conversion: improved: ExcludedBlueprintTypes list

	#codereview Dan.Oconnor

Change 2812316 on 2015/12/24 by Michael.Schoell

	Added more ByValue/ByRef test cases and added a way to dump all tests that are no longer succeeding.

	Tests Include:
	Verification that functions take and can modify by-ref values.
	ForEach loop verification. Tests for verifying that current functionality will continue to work after COPY injection and that "expected" functionality will work (and currently doesn't).
	More MegaArray tests.

Change 2812318 on 2015/12/24 by Michael.Schoell

	Usability fix: Duplicating graphs in the MyBP window will now open and focus the new graph.

Change 2813179 on 2015/12/29 by Michael.Schoell

	When promoting pins to variables, will no longer carry bIsReference, bIsConst, or bIsWeakPointer value to the new variable's type.

Change 2813435 on 2015/12/30 by Michael.Schoell

	Submitting by-value/by-ref testing BP with more tests:

	More "Set Members..." tests to catch edge cases.
	More Array tests.

Change 2813441 on 2015/12/30 by Michael.Schoell

[CL 2842166 by Mike Beach in Main branch]