Fixing UBT by removing unreferenced variable introduced by CL 2561288
Without this fix, UBT fails with error:

/UE4/Engine/Source/UE4Editor.Target.cs(243,13) : warning CS0219: The variable `AllBuildSettings' is assigned but its value is never used

ERROR: UnrealBuildTool encountered an error while compiling source files

#codereview kellan.carr

[CL 2561877 by Aaron McLeran in Main branch]