Copying //UE4/Dev-VR to //UE4/Dev-Main (Source: //UE4/Dev-VR @ 3764848) #lockdown Nick.Penwarden #rb no.one
============================
  MAJOR FEATURES & CHANGES
============================

Change 3632752 by Keli.Hlodversson

	Applying change 3632592 by Loren.McQuade@Loren.McQuade_Dev-VR_Branch on 2017/09/08 02:08:22

	     [Dev-VR] Push //UE4/Partner-Oculus@3632591 #rb merge
	     //UE4/Partner-Oculus to //UE4/Dev-VR/...

	Reverted OculusHMD_XRCamera changes, as that clas has been removed in the interim.

Change 3633211 by Mike.Beach

	Backing out Oculus MotionController hiding that accidently got submitted - we decided not to adopt this change originally.

Change 3640098 by Mike.Beach

	Switching the MR capture processing material to use a external sampler now (since that's what media textures are marked as now).

Change 3642021 by Mike.Beach

	Moving so MediaBlueprint header to Public so FMediaCaptureDevice can be used in other BP APIs (in other modules).

	#jira UEVR-910

Change 3642030 by Mike.Beach

	[WIP] Refactoring the MR capture component (along with the calibration level) so we can save off a reference to the video stream/format users select (adding a device selection step to calibration).

	#jira UEVR-910

Change 3645768 by Mike.Beach

	[WIP] Refining device selection/calibration so it reports which feeds error.

	#jira UEVR-910

Change 3646047 by Mike.Beach

	CIS linux fix.

Change 3646350 by Mike.Beach

	[WIP] Provide an ini setting which you can explicitly prioritize a format selection for MR calibration (reflects the list in editor).

Change 3664526 by Keli.Hlodversson

	#jira UE-50100

	Updated library revision for GoogleVR

	Unshelved from pending changelists '3646524', '3646526', '3646528'':

Change 3666500 by Keli.Hlodversson

	Fix -Wreorder compiler warnings

Change 3678564 by Douglas.Copeland

	Updating TM-HMDNodes LEvel BP to replace deprecated Tracking Sensor node

Change 3678919 by Mike.Beach

	Extending and renaming the XRSystemAssets interface. Plus fixing a few bugs found in the SteamVR implementation.

Change 3678920 by Mike.Beach

	Stubbing in Oculus support for a IXRSystemAssets implementation (currently using our own 'unofficial' models from the VREditor).

Change 3678922 by Mike.Beach

	Adding XR Blueprint library functions for accessing specific device information (tracking, modeling, etc.).

Change 3678941 by Mike.Beach

	CIS fixes for Dev-VR (fallout from CL 3678919)

Change 3679930 by Mike.Beach

	Adding native support to MotionController components, for rendering the associated device.

Change 3681153 by Mike.Beach

	Speculative fix for android CIS errors.

	#jira UE-50776

Change 3697385 by Keli.Hlodversson

	Fix broken OSVR build after removing IHeadMountedDisplay::GetHMDDeviceType()

Change 3697516 by Keli.Hlodversson

	Fix broken SimpleHMD build after removing IHeadMountedDisplay::GetHMDDeviceType()

Change 3698318 by Ryan.Vance

	Inverse can fail if we don't normalize the player's rotation.

Change 3698371 by Keli.Hlodversson

	GoogleVR projects fail to build: GoogleVRHMD.cpp(1175,110) : error: no member named 'ES2' in 'EShadingPath'
	#jira UE-51334

Change 3701479 by Mike.Beach

	Adding the ability to delay motion controller tracking for MR capture views (to better sync with camera feeds).

	#jira UEVR-908

Change 3703264 by Mike.Beach

	CIS fixes for linux (fallout from CL 3701479).

Change 3703792 by Ryan.Vance

	Disable mobile multi-view for Daydream if the gvr query for support fails.

Change 3704273 by Mike.Beach

	[WIP] The MRPlugin now auto spawns a MR capture actor if you have a MR config save file.

Change 3704524 by Mike.Beach

	MR Calibration - Enter key can now progress you through some of the prompts.

Change 3706679 by Mike.Beach

	Fixing issue with MotionController display models where the model component wouldn't be destroyed along with the MotionControllerComponent

Change 3707538 by Mike.Beach

	Hiding child actors along with the player in the MR capture.

Change 3714120 by Mike.Beach

	Adding new library function to transform tracking space positions/orientations into world space. And fixing EnumerateTrackedDevices/GetDevicePose, which weren't finding the appropriate tracking system.

Change 3716143 by Mike.Beach

	Speculative fix for XboxOne CIS issues.

Change 3719006 by Mike.Beach

	Removing some debug log spam that I accidently left in CL 3714120.

Change 3719774 by Mike.Beach

	Adding a scoped event name for the rift eye padding draw (so it shows up named in captures like from RenderDoc).

Change 3719778 by Mike.Beach

	Mirroring CL 3671849 from 4.18.

	Removing Oculus call to reset tracking origin on initialization (so we respect the play space that was calibrated in oculus setup) - ensuring parity w/ Vive (fixing regression).

	#jira UE-48260

Change 3736279 by Jeff.Fisher

	Touching a couple files to see if it helps the build machine by making it sync them again.

Change 3736296 by Jeff.Fisher

	Touching another file to kick the build machine into syncing it.

Change 3740060 by Ryan.Vance

	Removing PostInitViewFamily_RenderThread and PostInitView_RenderThread view extension callbacks.

Change 3744913 by Mike.Beach

	Fixing up the MotionDelayBuffer for MixedReality
	  - CIS fix when building for XboxOne
	  - Now works if late updating is disabled
	  - Switched to setting delay in millisecs and interpolating between samples
	  - Better handling for thread managment (was getting out of sync when focus was lost, etc.)
	  - Decoupled more from MotionControllerComponents (now polls separately, and uses its own LateUpdateManager to cache/apply)

	#jira UEVR-908

Change 3747168 by Jeff.Fisher

	UEVR-1018 MotionControllerComponent cleanup should be in beginDestroy, not Destructor
	-Moved ViewExtension cleanup to BeginDestory from destructor.
	-https://udn.unrealengine.com/questions/395504/strange-crash-in-umotioncontrollercomponent.html
	#review-3724080

	#jira UEVR-1018

Change 3753326 by Douglas.Copeland

	Resaving qagame content to resolve Empty Engine Version Warning

Change 3753336 by Douglas.Copeland

	Resolving more empty engine version content issues

Change 3754252 by Mike.Beach

	Mirroring CL 3723722 from 4.18.1

	Hotfix update from Oculus.

	  - Introduce dash support by adding an Oculus config setting (that is off by default)
	  - Move submission of the near plane╞s depth from a fixed one at texture allocation time to an every-frame one, which is needed for correct depth support in games that have a ⌠god mode÷ with a smaller worldtometersscale

	#jira UE-51728

Change 3754262 by Mike.Beach

	Mirroring 3726121 from 4.18.1

	Correcting a cpu perf regression from 4.17 - no longer calling FOculusHMDModule::Get() in what should be a cheap query function.

	#jira UE-51766

Change 3754278 by Mike.Beach

	Mirroring CL 3741384 from 4.18.1

	Fix from Oculus for GearVR crashing/freezing when quit menu is invoked - making sure JNI is attached to the render thread (after losing focus).

	#jira UE-52098

Change 3754300 by Mike.Beach

	Mirroring CL 3742608 from 4.18.1

	Fix from Oculus - improving perf on GearVR; keeping the window surface from scaling up to a size not required for Gear.

	#jira UE-52127

Change 3754319 by Mike.Beach

	Build fix - fallout from blindly adopting CL 3726121 from 4.18.1 w/out fixup (CL 3754262)

Change 3755546 by Keli.Hlodversson

	Marking a zombie header file for delete. Seems to get resurrected from the dead on every merge from main.
	File is no longer relevant as the OculusAudio plugin has been moved to the Plugins/Runtime/Oculus parent directory.

Change 3759716 by Mike.Beach

	Adopted chenges from Oculus (SI1.20)

	Manually modified files:
	  - DefaultXRCamera.cpp

	Rejected changes:
	  - SceneRenderTargets.cpp

	#jira UE-50855, UE-50883, UE-50950, UE-50974, UE-52427

Change 3760918 by Keli.Hlodversson

	Disable an ensure that had some false positives during the first few frames.
	#jira UE-52448

Change 3760946 by Keli.Hlodversson

	Missing SteamVR changes after deprecating RefreshPoses()
	#jira UEVR-1037

Change 3762015 by Mike.Beach

	CIS fix for android - fallout from Oculus 1.20 changes. Lib function was removed, with calls remaining on android (double checking with Oculus that this is the proper fix).

Change 3762236 by Ryan.Vance

	Fixing up integration issues.

Change 3763437 by Keli.Hlodversson

	Fix deprecation warning in SimpleHMD caused by removing RefreshPoses()

Change 3764713 by Ryan.Vance

	#jira UE-52516

	PSVR screen percentage was being disabled by default stereo layers on accident.


Change 3652413 by Mike.Beach

	In editor, only utilizing the HMD orientation when we're in a VR related mode (VR preview, VR editor, etc.). Not normalizing view pitch rotation unless we're in one of those modes.

	#jira UE-46724

Change 3690170 by Keli.Hlodversson

	Postprocessing now uses only the HMDDistortion flag to see whether a postprocessing pass is required for the current plugin instead of the older clutch that checks the plugin HMD type
	Added EShaderPath argument to GetHMDDistorionEnabled method so that the edge cases solved by the postprocessor and HMD type now can be handled by the plugins themselves.
	#jira UEVR-996

Change 3690625 by Keli.Hlodversson

	Remove IHeadMountedDisplay::GetHMDDeviceType() as it was added as a part of a clutch in postprocessing, but was later getting misused as a poor man's RTI even though a better alternative in IXRTrackingSystem::GetSystemName is already available.
	#jira UEVR-996

Change 3760773 by Keli.Hlodversson

	Update interfaces related to late update and begin rendering:
	* Deprecate RefreshPoses
	  Note: Existing and non-empty RefreshPoses implementations have been made private and non-virtual, and renamed to UpdatePoses in order not to conflict with the still-existing deprecated method in the base interface.
	* Rename BeginRendering_GameThread/RenderThread to OnBeginRendering_* and move them to IXRTrackingSystem instead of IHeadMountedDisplay.
	* Add bool DoesSupportLateUpdate() const to IXRTrackingSystem. IXRCamera implementations can use the method to see whether the underlying tracking system implementation supports late update. Note it is up to the IXRTrackingSystem implementations inside each plugin to actually make sure poses are updated somewhere before the late update is applied by the IXRCamera. (eg. in OnBeginRendering_RenderThread or ..._GameThread)
	* Move call to OnBeginRedering_RenderThread to happen before GetCurrentPose in FXRDefaultCamera so the plugin has a chance to refresh the poses inside its implementation of it.
	* Add IXRTrackingSystem::OnLateUpdateApplied_RenderThread, a method for notifying the tracking system that late update has been applied, passing in the current relative pose. Used by FXRTrackingSystemBase to pass the updated transform to the stereo layers implementation.
	#jira UEVR-1037

Change 3761781 by Mike.Beach

	Merging //UE4/Dev-Main to Dev-VR (//UE4/Dev-VR)

	Manually resolved files:
	  - OculusHMD.cpp
	  - OculusHMD_Settings.h/cpp
	  - SteamVRHMD.cpp
	  - PostProcessing.cpp
	  - OrionGame/Plugins/.../OnlineSessionInterface.h/cpp

[CL 3766571 by Mike Beach in Main branch]