Copying //UE4/Dev-Rendering to //UE4/Dev-Main (Source: //UE4/Dev-Rendering @ 2998063) #lockdown nick.penwarden
==========================
MAJOR FEATURES + CHANGES
==========================

Change 2981877 on 2016/05/18 by Rolando.Caloca

	DR - Fix some PVS warnings
	- Removed 'uniform' as a keyword on hlslcc as it's ignored/causes issues/doesn't really optimize
	#jira UE-30996

Change 2981966 on 2016/05/18 by Rolando.Caloca

	DR - Fix OpenGL crash quitting editor
	#jira UE-25549

Change 2982072 on 2016/05/18 by Uriel.Doyon

	Fixed a "Build Texture Streaming" crash related to custom outputs.
	Fixed issue with debug view mode and translucent primitives
	Fix bug with visibility that made some texture low res.
	Enabled per instance visibility in the texture streaming order (in game only).
	Improved InvestigateTexture Logs.
	Tweaked the mip computations from screen size.

Change 2982077 on 2016/05/18 by Uriel.Doyon

	Removed debug options!

Change 2982108 on 2016/05/18 by Olaf.Piesche

	#jira UE-30772
	moving AMD hacks to console variables

Change 2982422 on 2016/05/18 by Gil.Gribb

	UE4 - Potential crash fix on foliage occlusion queries and reflection captures.

Change 2982547 on 2016/05/18 by Martin.Mittring

	UE-26409 Crash when Light Propagation Volume Plugin is disabled on a Project

Change 2982548 on 2016/05/18 by Martin.Mittring

	Refactored MRT and outer Pixel Shader output to a struct
	to allow it passed in/out of functions allowing for a more readable code (less #ifdefs, reducing the boolean hell)
	Needed for upcoming MeshDecals

Change 2982601 on 2016/05/18 by Daniel.Wright

	Movable skylight now matches stationary for subsurface shading models
	* Two sided was broken in 4.11, Subsurface had never been handled

Change 2982603 on 2016/05/18 by Daniel.Wright

	DrawMaterialToRenderTarget / BeginDrawCanvasToRenderTarget now work correctly with material parameter collections and Time
	* FCanvas stores an optional scene to render to, UWorld caches the UCanvas needed for implementing these functions

Change 2982618 on 2016/05/18 by Daniel.Wright

	Better categories for some Rendering project settings

Change 2982619 on 2016/05/18 by Daniel.Wright

	Scene capture 2d improvements
	* Orthographic projection supported
	* Opacity is now captured in alpha, allows partial rendering in a scene capture and compositing into another scene later
	* Various GBuffer attributes are now available to be captured, including depth
	* Changed Blueprint capture function to CaptureScene, which happens immediately (was previously deferred), allowing multiple captures with different parameters

Change 2982664 on 2016/05/18 by Daniel.Wright

	Fading out planar reflections based on roughness since they don't have support for variable roughness (fade starts at .2 roughness, ends at .3)

Change 2982684 on 2016/05/18 by Martin.Mittring

	polish ImageValidator

Change 2982685 on 2016/05/18 by Martin.Mittring

	show testimage on sm4 as well

Change 2982736 on 2016/05/18 by Uriel.Doyon

	Improved overbudget retention logic.
	Updated ListStreamingTextures stats.

Change 2982854 on 2016/05/18 by Martin.Mittring

	ImageValidator can now save/load IVxml file

Change 2982863 on 2016/05/18 by Daniel.Wright

	Fixed shader compile error

Change 2982864 on 2016/05/18 by Daniel.Wright

	Removed deprecation message

Change 2982927 on 2016/05/18 by Martin.Mittring

	ImageValidator is now sorting by time

Change 2983743 on 2016/05/19 by Chris.Bunner

	Saturated tri-planar UV function outputs to prevent negative blending
	#jira UE-30964

Change 2983747 on 2016/05/19 by Martin.Wilson

	Fix for morph curves not getting applied to meshes in cooked builds (smart names were not being corrected).

Change 2984008 on 2016/05/19 by Brian.Karis

	New contact shadows feature.

	Hair uses ray cast for nonshadow lights

Change 2984009 on 2016/05/19 by Brian.Karis

	changed to ShadowedBits

Change 2984054 on 2016/05/19 by Brian.Karis

	Deleted old motion blur

Change 2984420 on 2016/05/19 by Daniel.Wright

	Shorter display name for WorldPosition material node

Change 2984423 on 2016/05/19 by Daniel.Wright

	Fixed WorldPosition and ScreenPosition for downsampled separate translucency by scaling SvPosition before those computations.  The View uniform buffer still contains incorrect buffer sizes for this pass.

Change 2984432 on 2016/05/19 by Rolando.Caloca

	DR - Disable PPCombineLUT for Vulkan to work around glslang issue (will need to be reenabled when adding SM4/5 path)

Change 2985415 on 2016/05/20 by Daniel.Wright

	Added a Texture2D exporter for .hdr
	Texture2D exporters now implement SupportsObject properly, so you only see extensions that are valid based on the format

Change 2985439 on 2016/05/20 by Daniel.Wright

	Scene color alpha clear value validation

Change 2987173 on 2016/05/23 by Martin.Mittring

	ImageValidator Report with Thumbnail (cannot be copied and pasted into email), non Thumbnail version could be.

Change 2987248 on 2016/05/23 by Martin.Mittring

	ImageValidator: added Summary, removed timer hack

Change 2987369 on 2016/05/23 by Martin.Mittring

	ImageValidator polish

Change 2987390 on 2016/05/23 by Brian.Karis

	Improvement to temporal aa sharpness and speed.

Change 2988038 on 2016/05/24 by Gil.Gribb

	Merging //UE4/Dev-Main@2987977 to Dev-Rendering (//UE4/Dev-Rendering)

Change 2988304 on 2016/05/24 by Martin.Mittring

	added const to prevent coding errors

Change 2988332 on 2016/05/24 by Brian.Karis

	Fixed motion blur crash on SM4

Change 2988446 on 2016/05/24 by Martin.Mittring

	nicer UI

Change 2988990 on 2016/05/24 by Martin.Mittring

	fixed UE-31227 Building lighting produces bad results
	#jira:UE-31227

Change 2989729 on 2016/05/25 by Uriel.Doyon

	Fixed lightmaps and shadowmaps having low resolutions after building the lighting.
	#jira UE-31254

Change 2989752 on 2016/05/25 by Olaf.Piesche

	CVar to disable/freeze GPU particle simulation

Change 2989811 on 2016/05/25 by Daniel.Wright

	Making use of MATERIALBLENDING_ANY_TRANSLUCENT

Change 2989812 on 2016/05/25 by Daniel.Wright

	Hide DFGI show flags from UI

Change 2989901 on 2016/05/25 by Daniel.Wright

	Height fog now works properly in planar reflections
	* The ray used for computing fog is first clipped by the reflection plane

Change 2989904 on 2016/05/25 by Daniel.Wright

	Always use PF_FloatRGBA for LightAccumulation to guarantee alpha channel and negative range

Change 2989991 on 2016/05/25 by Daniel.Wright

	Improved usability for DBuffer Decals
	* 'Show Decals' works correctly, previously would fetch from uninitialized textures
	* DBuffer being enabled forces a full prepass, previously decals would render incorrectly unless correct settings of r.EarlyZPass were used
	* Improved the PrePass draw event to indicate whether it's full or partial
	* Materials using DBuffer blend modes will fail to compile when the DBuffer project setting is disabled, instead of just being invisible
	* r.EarlyZPass can now be changed at runtime, which is useful for profiling

Change 2990008 on 2016/05/25 by Daniel.Wright

	Fixed capsule shadows on skeletal meshes with scaling

Change 2990274 on 2016/05/25 by Daniel.Wright

	Fixed DFAO (from cl 2961310)

Change 2990304 on 2016/05/25 by Martin.Mittring

	OR-22233 GPU Sprites invisible unless solo'd
	#jira:OR-22233

Change 2990309 on 2016/05/25 by Martin.Mittring

	Added SubDSurface actor (using CPU code of OpenSubDiv), component, asset as starting point for more work in that direction,
	(Early work in progress)

Change 2990363 on 2016/05/25 by Daniel.Wright

	Spreading precomputed visibility to neighbors now uses a 2d grid to find neighbors, speeds up the process for 800k cells from 40 mins to 20s

Change 2990392 on 2016/05/25 by Daniel.Wright

	Added r.AOSpecularOcclusionMode, which determines how specular should be occluded by DFAO
	0: Apply non-directional AO to specular.
	1: (default) Intersect the reflection cone with the unoccluded cone produced by DFAO.  This gives more accurate occlusion than 0, but can bring out DFAO sampling artifacts.
	2: (experimental) Cone trace through distance fields along the reflection vector.  Costs about the same as DFAO again because more cone tracing is done, but produces more accurate occlusion.

Change 2990454 on 2016/05/25 by Martin.Mittring

	polish readme

Change 2990610 on 2016/05/25 by Martin.Mittring

	fixed building with VS2015, the right OpenSubDiv .lib files are missing, temporarily disabled the relevant code
	#code_review:Shane.Caudle

Change 2990754 on 2016/05/25 by Zabir.Hoque

	Fix compiler warning: C4456: declaration of 'NewStaticMesh' hides previous local declaration.

	#CodeReview: Martin.Mittring

Change 2990801 on 2016/05/25 by Zabir.Hoque

	Only allocate reflection capture cubemaps if we are actually doing a reflection capture. The old approach always allocated based on CVar and worked with a warning on D3D since if SRC was larger than the DST, the extra SRC area was dropped. New approach only allocates when necessary and is correctly sized everytime. Also hardened access to CVar and what users are allowed to set.

	#CodeReview Marcus.Wassmer, Rolando.Caloca, Daniel.Wright, Martin.Mittring

Change 2991169 on 2016/05/26 by Martin.Mittring

	fixed compiler warning
	WARNING: Non-editor build cannot depend on non-redistributable modules. Details:
	#lockdown: gil.gribb

Change 2991238 on 2016/05/26 by Martin.Mittring

	fixed build
	fatal error C1083: Cannot open include file: 'RawMesh.h': No such file or directory  (when RawMesh is not part of PrivateDependencyModuleNames in Engine.Build.cs)
	#lockdown:Gil.Gribb

Change 2991726 on 2016/05/26 by Daniel.Wright

	Subsurface materials are now handled with simple forward shading
	#jira OR-22237
	#lockdown gil.gribb

Change 2991727 on 2016/05/26 by Daniel.Wright

	Emissive decals are now supported with simple forward shading
	#jira OR-22282
	#lockdown Gil.Gribb

Change 2994849 on 2016/05/31 by Daniel.Wright

	Disabled fix for WorldPosition and ScreenPosition in downsampled separate translucency, since it breaks GetScreenAlignedUV (used in DepthFade), since the uniform buffer still contains full res buffer sizes
	#lockdown Gil.Gribb

Change 2997243 on 2016/06/01 by Gil.Gribb

	Merging //UE4/Dev-Main@2996565 to Dev-Rendering (//UE4/Dev-Rendering)
	#lockdown nick.penwarden

[CL 2998067 by Gil Gribb in Main branch]