Fix for "ignored qualifiers" warning issued by clang 3.5.0
- The change is authored by Steve Robb.
- Can make code more efficient by passing some args by value.
- Ugly due to typename not allowed outside of templates by MSVC (error C2899).

#codereview Mike.Fricker, Josh.Adams, Nick.Penwarden, Steve.Robb, Michael.Trepka, Marcus.Wassmer, Gil.Gribb

[CL 2287913 by Dmitry Rekman in Main branch]