EMapChangeType is strongly types, so it can be forward-declared.
NonUnityTestCompile_OnMac Cis fix: "ISequencer.h:162:56: error: unknown type name 'EMapChangeType'"

#codereview Max.Preussner

[CL 2627106 by Maciej Mroz in Main branch]