Removing a stray unused var that's causing some mac build issues.
Fixes:
sh: IPhonePackager/Utilities.cs(451,13): error CS0219: Warning as Error: The variable `DictionaryNode' is assigned but its value is never used

#codereview Josh.Adams

[CL 2187492 by Terence Burns in Main branch]