Fixed Mac CIS compile regression
mono: Developer/ProjectLauncher/Private/Widgets/Cook/SProjectLauncherCookByTheBookSettings.h:161:56: error: extra qualification on member 'HandleDLCIncludeEngineContentCheckBoxIsChecked'

[CL 2517846 by Mike Fricker in Main branch]